In [1]:
from pathlib import Path
import pandas as pd

In [2]:
# TODO:
#  periods at the end of sentences

In [3]:
word_doc_training_data = Path("../../Data/worddoc_final_df.pickle")

df = pd.read_pickle(word_doc_training_data)
cols = [
    'OCR_issue', 'exclude_len_ratio', 'exclude_verb_ratio', 'exclude_noun_ratio',
    'exclude_entity_ratio', 'exclude_clause_ratio', 'exclude_figtext', 'exclude_too_short', 'has_date_refs',
    'unmatched_lexical_constraints', 'has_number_mismatch', 'exclude_wrong_language', 'is_duplicate'
]
df['n_exclusion_triggers'] = df[cols].sum(axis=1)

In [4]:
df[~df.exclude].sample(22)

,document_name,fr,en,similarity,len_ratio,verb_ratio,noun_ratio,entity_ratio,clause_ratio,OCR_issue,...,exclude_clause_ratio,exclude_figtext,exclude_too_short,has_date_refs,unmatched_lexical_constraints,has_number_mismatch,exclude_wrong_language,is_duplicate,exclude,n_exclusion_triggers
1036,PRO-CR2024-035 MAR,Le présent document inclut un résumé des prése...,This proceedings document includes a summary o...,0.938,1.016000,1.500000,0.888889,1.000000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
76062,RES2025-048 NL,Estimations de la taille du stock de morue du ...,Northern cod stock size estimates with lower a...,0.794,1.326923,1.000000,1.125000,1.000000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
114717,RES2026-015 QC,Positions des casiers lors du relevé post-sais...,Trap positions during the post-season survey i...,0.762,1.157895,2.000000,1.000000,0.333333,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
115058,RES2026-016 NL,Les strates en noir étaient incomplètes.,Strata in black were incomplete.,0.732,1.250000,1.000000,1.000000,1.000000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
91055,RES2025-070 NCR,Sa capacité à se rétablir est désormais limité...,Its ability to recover is now constrained by t...,0.892,1.274194,1.000000,1.000000,1.000000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
126360,SAR-AS2025-014 QC,Ceux-ci sont répartis dans le golfe du Saint-L...,These stocks are distributed in the Gulf of St...,0.773,0.983333,1.000000,1.500000,1.000000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
687,PRO-CR2024-033 MAR,On avance que les documents de travail examiné...,It was stated that the Working Papers reviewed...,0.917,1.090909,1.250000,3.000000,0.333333,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
6622,PRO-CR2024-048 NL,Un coauteur souligne que la première année imp...,A co-author outlined that the first year would...,0.946,1.066298,0.750000,1.000000,0.333333,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
6778,PRO-CR2024-048 NL,Étendre l'analyse de puissance de l'accent mis...,Expand the power analysis from its species-foc...,0.932,1.478261,1.333333,1.000000,1.000000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
153664,SRR-RS2026-003 PAC,"L'identifiabilité est également un enjeu, car ...","Identifiability is also an issue, as several c...",0.923,1.328431,1.666667,1.083333,0.333333,1.333333,False,...,False,False,False,False,False,False,False,False,False,0
59875,RES2025-029 QC,"De plus, pour atténuer la mortalité liée à la ...","Additionally, to reduce the risk of size-relat...",0.864,1.080808,1.000000,0.833333,0.500000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
79222,RES2025-054 QC,"Selon l'approche actuelle, la structure d'âge ...","Under the current approach, the model estimate...",0.879,1.084615,1.333333,1.000000,1.000000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
118491,SAR-AS2024-053 NL,Les indicateurs courants de la biodiversité so...,Common indicators for biodiversity are taxa ri...,0.902,1.427481,1.000000,1.222222,1.000000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
16309,RES2024-060 MAR,"D'un point de vue pratique, l'élaboration d'un...","From a practical standpoint, statistical model...",0.921,1.113122,1.333333,1.230769,0.500000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
115549,SAR-AS2024-002 NL,L'analyse des traits jumelés entre les anciens...,Analyses of paired tows between old and new ve...,0.850,1.253968,1.000000,1.000000,1.000000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
114714,RES2026-015 QC,Positions des casiers lors du relevé post-sais...,Trap positions during the post-season survey i...,0.766,1.155172,2.000000,1.000000,0.333333,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
408,PRO-CR2024-033 MAR,Elles ne plongent pas aussi profondément que l...,They do not dive as deep as northern bottlenos...,0.852,1.327273,1.000000,1.000000,1.000000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
111507,RES2026-010 QC,L'aire des cercles est proportionnelle à la va...,The surface area of the circles is proportiona...,0.923,0.888060,1.000000,1.000000,1.000000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
331,PRO-CR2024-033 MAR,Les amarrages fixes ne permettent pas de résou...,"With fixed moorings, anything spatial cannot b...",0.755,1.272727,1.250000,1.000000,1.000000,0.666667,False,...,False,False,False,False,False,False,False,False,False,0
122939,SAR-AS2025-004 MAR,Diverses sources de données et méthodologies o...,Various data sources and methodologies were in...,0.955,1.108108,1.000000,1.000000,1.000000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
148643,SRR-RS2025-024 NL,Est-ce que l'une de ces populations est inscri...,Are any of these populations listed under Sche...,0.716,1.183908,1.000000,2.333333,0.666667,1.000000,False,...,False,False,False,False,False,False,False,False,False,0
36909,RES2025-007 NL,Il est nécessaire d'accroître la fréquence et ...,Increased survey frequency and coverage is nec...,0.852,1.341176,1.000000,1.000000,1.000000,1.000000,False,...,False,False,False,False,False,False,False,False,False,0

In [5]:
df['exclude'].value_counts()

exclude
True     132307
False     22562
Name: count, dtype: int64

In [6]:
df[[
    'similarity', 'len_ratio', 'verb_ratio', 'noun_ratio', 'entity_ratio', 'clause_ratio',
]].describe(include='all').T

,count,mean,std,min,25%,50%,75%,max
similarity,154869.0,0.891979,0.092352,0.700000,0.818,0.897000,1.00000,1.000000
len_ratio,154869.0,1.169706,0.224098,0.144144,1.000,1.140127,1.27907,12.166667
verb_ratio,154869.0,1.094908,0.468705,0.125000,1.000,1.000000,1.00000,7.000000
noun_ratio,154869.0,1.538989,1.114915,0.076923,1.000,1.200000,1.75000,25.000000
entity_ratio,154869.0,0.888729,0.535801,0.041667,0.500,0.909091,1.00000,10.000000
clause_ratio,154869.0,1.077233,0.425812,0.062500,1.000,1.000000,1.00000,12.000000

In [7]:
df[[
    'OCR_issue', 'exclude_len_ratio', 'exclude_verb_ratio', 'exclude_noun_ratio',
    'exclude_entity_ratio', 'exclude_clause_ratio', 'exclude_figtext', 'exclude_too_short', 'has_date_refs',
    'unmatched_lexical_constraints', 'has_number_mismatch', 'exclude_wrong_language', 'is_duplicate',
    'exclude'
]].apply(pd.Series.value_counts).T

                                False   True
OCR_issue                      128037   26832
exclude_len_ratio              149455    5414
exclude_verb_ratio             149527    5342
exclude_noun_ratio             143432   11437
exclude_entity_ratio           148494    6375
exclude_clause_ratio           138130   16739
exclude_figtext                139358   15511
exclude_too_short              137109   17760
has_date_refs                  110121   44748
unmatched_lexical_constraints  119575   35294
has_number_mismatch            144720   10149
exclude_wrong_language          91324   63545
is_duplicate                   149430    5439
exclude                         22562  132307

In [17]:
n_samples = 5

for exclusion in cols:
    print(f"\n{exclusion}")
    display(df.loc[
        (df['n_exclusion_triggers'] == 1) & (df[exclusion]),
        df.columns[:4]
    ].sample(n_samples))

OCR_issue

,document_name,fr,en,similarity
32565,RES2025-001 PAC,Nous avons sélectionné toutes les lignes qui c...,We selected all lines that contain eelgrass ob...,0.848
39298,RES2025-011 NCR,Un traitement était efficace à 90 dans des exp...,A treatment was 90 effective in field experime...,0.961
31310,RES2024-079 PAC,"L'abondance prévue une année donnée, y, et un ...","The expected abundance on a given year, y, and...",0.897
20212,RES2024-068 MAR,Les pinnipèdes dispersés étaient considérés co...,Dispersed pinnipeds were considered more vulne...,0.846
55985,RES2025-024 PAC,"De plus, du fait de l'incertitude dans les don...","Further, uncertainty in the data, including th...",0.905

exclude_len_ratio

,document_name,fr,en,similarity
19879,RES2024-068 MAR,Planification de l'intervention aux échelles l...,Area and Regional Response Planning,0.830
107368,RES2026-005 NCR,Les apports des rivières dans la région sont p...,The region has no large river inputs.,0.752
132642,SAR-AS2025-035 MAR,Les étiquettes à TPI réduisent les risques ass...,PIT tags reduce the chance of marks being miss...,0.727
48099,RES2025-014 PAC,Les quatre méthodes en question sont les suiva...,The four methods include:,0.960
38539,RES2025-010 MAR,"Err0 : en tant que valeur de base, mais aucune...","Err0: as Base, but no observation error in SSB",0.841

exclude_verb_ratio

,document_name,fr,en,similarity
12888,RES2024-051 MAR,Les âges ont été déterminés à partir d'échanti...,Ages were determined from scale samples.,0.794
72325,RES2025-044 NL,Il existe une incertitude quant à la façon don...,There is uncertainty in how the landings were ...,0.943
138695,SAR-AS2026-004 NL,La présente publication doit être citée comme ...,Correct citation for this publication:,0.703
60785,RES2025-030 GLF,Figure A12 : Diagnostics modélisés pour le mod...,Figure A12: Model diagnostics for the Atlantic...,0.859
5606,PRO-CR2024-047 NL,Sud de Terre-Neuve : échantillonnage à l'appui...,South Newfoundland: Sampling to support a poss...,0.732

exclude_noun_ratio

,document_name,fr,en,similarity
50952,RES2025-018 NL,Secrétariat canadien des avis scientifiques (S...,Canadian Science Advisory Secretariat (CSAS),0.872
142070,SRR-RS2024-035 O&P,"Lee Gutowsky, MPO Science, Région de l'Ontario...","Lee Gutowsky, DFO Science, Ontario and Prairie...",0.914
120840,SAR-AS2024-063 NL,"Rapport d'évaluation de base, y compris les vi...","Baseline Assessment Report, including Benthic ...",0.759
29642,RES2024-077 MAR,Le sud du golfe du Saint-Laurent comme habitat...,The Southern Gulf of St. Lawrence as Foraging ...,0.895
131134,SAR-AS2025-030 NL,Tendances et trajectoires historiques et récen...,Historical and Recent Stock Trajectory and Trends,0.941

exclude_entity_ratio

,document_name,fr,en,similarity
96401,RES2025-076 NL,"Lignes continues CPUE normalisées, lignes poin...","Solid line standardized CPUE, dotted lines raw...",0.821
102457,RES2025-083 MAR,Les points de référence utilisés dans ce scéna...,The reference points used in this scenario are...,0.863
48921,RES2025-015 NCR,Insérer l'échantillon de 5 mL dans la fiole da...,Dispense the 5 mL sample into the vial for a 1...,0.835
109324,RES2026-007 QC,Une approche de modélisation et de conceptuali...,A survey design-based and modelling approach w...,0.804
52179,RES2025-021 NL,Les traits jumelés ont échantillonné des habit...,Paired sets sampled nearly identical benthic h...,0.858

exclude_clause_ratio

,document_name,fr,en,similarity
58864,RES2025-027 GLF,Pêches et Océans Canada Secrétariat canadien d...,Fisheries and Oceans Canada Canadian Science A...,0.902
94193,RES2025-074 QC,"Lorsque les a priori étaient exclus, la BSR ét...",When the priors were excluded SSB was greater ...,0.755
101000,RES2025-081 NCR,"Aux termes de la Politique sur l'AP, les princ...",Under the PA Policy the primary components of ...,0.794
93082,RES2025-072 NCR,Nuncor est l'estimation non corrigée;,Nuncor is the uncorrected estimate,0.854
23159,RES2024-068 MAR,Association avec des substrats non consolidés ...,Associated with unconsolidated substrates (sil...,0.787

exclude_figtext

,document_name,fr,en,similarity
26656,RES2024-073 NL,1 Analyses basées sur la fermeture complète de...,1 Analyses based on entire 3O coral closure; 2...,0.924
73603,RES2025-046 PAC,Le tableau 14 énumère les valeurs propres à ch...,Table 14 lists the specific values for each of...,0.942
133040,SAR-AS2025-037 NL,L'estimation du facteur de conversion selon la...,Estimates of the conversion factor at length f...,0.966
130947,SAR-AS2025-029 QC,"Depuis quatre ans, la taille moyenne des mâles...","For the past four years, the average size of l...",0.964
15237,RES2024-058 GLF,La pêche à engins fixes se concentre dans la z...,The fixed gear fishery is focused in NAFO Divi...,0.806

exclude_too_short

,document_name,fr,en,similarity
109095,RES2026-006 NCR,Les unités sont en mètres.,Units are metres.,0.858
108133,RES2026-006 NCR,Les unités sont en mètres.,Units are metres.,0.858
111846,RES2026-011 QC,Nous avons supposé que,We assumed that,0.784
7430,RES2023-086 QC,Nous avons supposé que,We assumed that,0.784
6628,PRO-CR2024-048 NL,Nous avons évalué,We evaluated,0.839

has_date_refs

,document_name,fr,en,similarity
147884,SRR-RS2025-019 GLF,Les sources d'incertitude liées à l'acquisitio...,Sources of uncertainty relating to data acquis...,0.915
126887,SAR-AS2025-017 QC,"En revanche, ils étaient très faibles dans la ...","In contrast, they were very low in the La Roma...",0.851
82657,RES2025-059 NCR,Bien que de vastes zones au large de la côte d...,Although there were large areas identified off...,0.953
153835,SRR-RS2026-004 MAR,"Entre 2024 et 2025, le taux d'exploitation pro...","Between 2024 and 2025, the realized proportion...",0.923
143050,SRR-RS2024-037 MAR,Un échantillonnage a été effectué à la CNPL af...,Sampling was undertaken at the PLNGS to determ...,0.745

unmatched_lexical_constraints

,document_name,fr,en,similarity
81631,RES2025-058 QC,Trois vallées (les vallées de Bradelle Ouest e...,Three valleys (Western and Eastern Bradelle va...,0.884
48888,RES2025-015 NCR,Calculer la concentration réelle de sulfures c...,Calculate the actual sulfide concentration using:,0.867
38112,RES2025-009 NL,Le LFDCS n'a détecté que 4 à 28 des appels ton...,LFDCS only detected 4 28 of BW tonal calls.,0.788
37820,RES2025-008 GLF,Ces déclins ont été liés à une multitude de fa...,The declines have been linked to a multitude o...,0.947
100203,RES2025-080 NL,Dans les premières années qui ont suivi l'expa...,In the early years following the fishery expan...,0.850

has_number_mismatch

,document_name,fr,en,similarity
73624,RES2025-046 PAC,La ligne continue rouge représente la moyenne ...,Red solid line represents the 4-year running g...,0.812
49875,RES2025-017 NCR,L'incertitude associée à la moyenne pondérée e...,The uncertainty associated with the weighted m...,0.717
50772,RES2025-018 NL,"Par exemple, l'utilisation du LFDCS avec la bi...","For example, using LFDCS with the Gom9 call li...",0.710
73577,RES2025-046 PAC,Comparaison des estimations du GRMD pour neuf ...,Comparison of SMSY estimates for 9 spawner-adu...,0.704
16017,RES2024-060 MAR,"La maraîche a été interceptée dans 11,1 à 40 d...",Porbeagle were intercepted on 11.1 40 of obser...,0.772

exclude_wrong_language

,document_name,fr,en,similarity
41022,RES2025-011 NCR,Aqua Info Aquaculture Notes.,Aqua Info Aquaculture Notes.,1.000
40697,RES2025-011 NCR,Abundance and spread of the invasive red algae...,Abundance and spread of the invasive red algae...,1.000
9674,RES2023-090 NL,"Sekerak, A.D., Buchanan, R.A., Griffiths, W.B....","Sekerak, A.D., Buchanan, R.A., Griffiths, W.B....",1.000
151680,SRR-RS2025-028 NL,Memorial University of Newfoundland.,Memorial University of Newfoundland.,1.000
41588,RES2025-011 NCR,Caprelle japonaise (Caprella mutica),Japanese skeleton shrimp Caprella mutica,0.761

is_duplicate

,document_name,fr,en,similarity
111203,RES2026-010 QC,Les quatre dernières lignes indiquent les cont...,The last four rows show the contributions (in ...,0.853
22913,RES2024-068 MAR,Aucune donnée d'évaluation récente de la popul...,No recent population assessment information wa...,0.944
133143,SAR-AS2025-037 NL,Conversion nécessaire pour la biomasse,Conversion required for biomass,0.988
68386,RES2025-039 QC,Estimations du modèle de quantités selon l'âge...,Model estimates of age-based quantities define...,0.878
23617,RES2024-068 MAR,Aucun signe d'endémisme ou d'isolement dans la...,No evidence of endemism or isolation within th...,0.875